version: '3.8'

services:
  frontend:
    build: .
    # build: ./frontend
    container_name: tailwind-learning
    ports:
      - "3000:3000"
    volumes:
        - .:/app
        # - ./frontend:/app
        - /app/node_modules
    networks:
      - mynetwork
    env_file:
      - frontend.env
    # depends_on:
    #   - backend

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - backend.env
  #   networks:
  #     - mynetwork

networks:
  mynetwork: