version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Ensure this Dockerfile is tailored for the frontend
    container_name: asbdubby-prod
    ports:
      - "3000:3000"

    env_file:
      - .env.production
    networks:
      - mynetwork

networks:
  mynetwork: